# Generated by Django 4.2.16 on 2024-09-23 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_taskentries'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskentries',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskentries',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
