# Generated by Django 4.2.16 on 2024-09-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_taskentries_created_on_taskentries_modified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskentries',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='taskentries',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
