# Generated by Django 4.2.16 on 2024-09-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_taskentries_total_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskentries',
            name='total_duration',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='taskentries',
            unique_together={('user', 'task', 'start_time')},
        ),
    ]
