# Generated by Django 4.2.16 on 2024-09-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_taskentries_total_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskentries',
            unique_together={('user',)},
        ),
    ]
